BL-8537 Fix caption
BloomBooks/comical-js pull request #79
Opened 2021-01-19 18:14 UTC by gmartin7

* shadowOffset (a feature of captions) was opaque,
   now we turn it off if there is transparency in the
   background

2021-01-19 18:48 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/79)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/bubble.ts, line 283 at r1](https://reviewable.io/reviews/bloombooks/comical-js/79#-MRQwcUW0RbhobWX88yX:-MRQwcUX5L-i7k2AvqSy:bc0t6in) ([raw file](https://github.com/bloombooks/comical-js/blob/7c7cd6036aaf1d9c99c50ad018999b0b06033ef4/src/bubble.ts#L283)):*
> ```XML
>         if (this.containsTransparencyInBackground(mergedBubble)) {
>             mergedBubble.shadowOffset = undefined; // shadowOffset is opaque
>         }
> ```

This is just showing my ignorance of how this part of the system works,
but what happens if the user has a caption, sets the color as partially transparent thus losing the shadow, then makes it opaque again? Have they permanently lost the shadow?

Do we need to add a test for this?
___
*[src/bubble.ts, line 294 at r1](https://reviewable.io/reviews/bloombooks/comical-js/79#-MRQx5a47oNhEEh-6DSw:-MRQx5a47oNhEEh-6DSx:b1q5f9i) ([raw file](https://github.com/bloombooks/comical-js/blob/7c7cd6036aaf1d9c99c50ad018999b0b06033ef4/src/bubble.ts#L294)):*
> ```XML
>             const backColor = backColorArray[0];
>             if (backColor.startsWith("rgba")) {
>                 const regex = /,\s0\./;
> ```

Seems like this could be more robust. For one thing, this requires one and only one whitespace character before the 0.
How about removing the first check for startsWith rgba and doing
`/rgba\(\s*\d+,\s*\d+,\s*\d+,\s*0\.\d+\)/` instead?


<!-- Sent from Reviewable.io -->

2021-01-19 19:30 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/79)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/bubble.ts, line 283 at r1](https://reviewable.io/reviews/bloombooks/comical-js/79#-MRQwcUW0RbhobWX88yX:-MRR4-4--30r4gnQq0j5:b-cs00we) ([raw file](https://github.com/bloombooks/comical-js/blob/7c7cd6036aaf1d9c99c50ad018999b0b06033ef4/src/bubble.ts#L283)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is just showing my ignorance of how this part of the system works,
but what happens if the user has a caption, sets the color as partially transparent thus losing the shadow, then makes it opaque again? Have they permanently lost the shadow?

Do we need to add a test for this?
</blockquote></details>

Actually I just tested this and the bubbleSpec merging method is smart enough that the shadow comes back as soon as a caption is made opaque again.
___
*[src/bubble.ts, line 294 at r1](https://reviewable.io/reviews/bloombooks/comical-js/79#-MRQx5a47oNhEEh-6DSw:-MRR4CTX2YXSTJN62BNc:bp65b02) ([raw file](https://github.com/bloombooks/comical-js/blob/7c7cd6036aaf1d9c99c50ad018999b0b06033ef4/src/bubble.ts#L294)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like this could be more robust. For one thing, this requires one and only one whitespace character before the 0.
How about removing the first check for startsWith rgba and doing
`/rgba\(\s*\d+,\s*\d+,\s*\d+,\s*0\.\d+\)/` instead?
</blockquote></details>

Excellent! Will do. (I had meant to make that whitespace zero or more, but failed to do so.) :(


<!-- Sent from Reviewable.io -->

2021-01-19 20:26 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/79)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/bubble.ts, line 294 at r1](https://reviewable.io/reviews/bloombooks/comical-js/79#-MRQx5a47oNhEEh-6DSw:-MRRJpmF4z6o8OiSXgUR:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/7c7cd6036aaf1d9c99c50ad018999b0b06033ef4/src/bubble.ts#L294)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Excellent! Will do. (I had meant to make that whitespace zero or more, but failed to do so.) :(
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 20:40 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-01-19 20:41 UTC, andrew-polk approved these changes
Waiting for "UI Review" but really a design decision.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/79#-:-MRRNFYn7DGDYK80nJDa:b-2viadm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-03-01 23:00 UTC, closed without merging

2021-03-01 23:01 UTC, gmartin7 commented
We're going a different direction with BL-8537 and BL-8194.